### PR TITLE
Added check to try to use prior date

### PR DESCRIPTION
**Pull request by Ralac07**
Added check for msg.date and uses it as the date if it exists, otherwise uses current date/time

this is my first time making a pull request, I hope I got it right

### CODE REVIEW

**Comment by Paul-Reed** [comment]
Hi Ryan, thanks for your PR.
The changes to simpletime.js are OK, but your changes to the readme would delete my existing readme txt and replace it with "# This is a fork, use the original instead". 

If you can edit your PR, or submit a new PR just for the changes to simpletime.js I can update the readme at my end.

Thanks
Paul

**Comment by Ralac07** [comment]
I reverted the README.md file, Is that good? I'm not very experienced with GitHub

**Comment by Paul-Reed** [comment]
Thanks Ryan. Looks good to me, and I will hopefully get some time over the weekend to merge it.
(I've been away from home for a few days)

**Comment by Paul-Reed** [comment]
Thank you Ryan, I'll update the readme, publish a new version, and put a post in the node-RED forum.

**Pull request merged**
